Gallery router hook handling #28
EDMdesigner/superserverjs pull request #29
Opened 2017-04-10 16:46 UTC by derPuntigamer

2017-04-10 16:48 UTC, derPuntigamer commented on src/router/crud.js
> -		console.log(req.lol);
lol, ez eddig bent volt...

2017-04-10 16:51 UTC, derPuntigamer commented on src/router/gallery.js
> +		// avoid accidentally apply id to the filter from preHooks
például a /:APIkey/:belongsTo/:id esetén az id is automatikusan a filter-re kerül. Ezt lehet kezelni a prehookban is, ez csak egy extra réteg biztonság.

2017-04-11 04:17 UTC, gyulanemeth requested changes

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +		config.validMimeTypes.constructor === Array)) {
If you put the condition into multiple lines, then the { should go to a new line, so it's clear where the block actually starts.

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +	/*
Do we really need these? :P

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/crud.js
> -		console.log(req.lol);
lol indeed. :)

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> -		var filter = createFilterObjFromParams({
Ha jól sejtem, most minden filter funkcionalitás kikerült a hookokra... ugye?

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +		// avoid accidentally apply id to the filter from preHooks
ok

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +	var getParams = ["/"];
Először az innentől a POST feliratig tartó kódot nem értettem, aztán ahogy végignéztem a kódot jöttem rá, hogy itt fűzöd fel a megfelelő paraméterezéssel a routerre a dolgokat. (A megfelelő prehookokkal.)

Talán a biztonság kedvéért itt még annyi ellenőrzést meg lehetne ejteni, hogy ha arrayről van szó, akkor az elemei legyenek function-ök.

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +		// avoid accidentally apply id to the filter from preHooks
a többi /:id végűnél miért nincs ilyen?

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +				// execute delete posthook when all the delete tasks are don
done

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +					config.postHooks.delete();
can't it be an array of functions?

2017-04-11 04:17 UTC, gyulanemeth commented on src/router/gallery.js
> +	if (config.preHooks.delete) {
I see this pattern for the 4th time. Can you create a function out of it?

2017-04-11 11:31 UTC, derPuntigamer commented on src/router/gallery.js
> -		var filter = createFilterObjFromParams({
Pontosan :hammer:

2017-04-11 11:50 UTC, gyulanemeth requested changes

2017-04-11 11:50 UTC, gyulanemeth commented on src/router/gallery.js
> +		let key = Object.keys(query.find)[0];
This can crash if find is {}.

2017-04-11 11:53 UTC, gyulanemeth approved these changes

2017-04-11 11:55 UTC, gyulanemeth approved these changes

2017-04-11 11:55 UTC, merged